config/routes.rb
GeocoderApp1::Application.routes.draw do
  resources :locations

  match 'login' => 'locations#login'
  match '/auth/:provider/callback' => 'sessions#create'
  match '/signout' => 'sessions#destroy', :as => :signout
  match '/signin' => 'sessions#new', :as => :signin

   root :to => 'locations#new'

end

app/models/location.rb
class Location < ActiveRecord::Base
  attr_accessible :address, :latitude, :longitude
    geocoded_by :address
   after_validation :geocode, :if => :address_changed?
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :name, :provider, :uid

 def self.create_with_omniauth(auth)
  create! do |user|
    user.provider = auth['provider']
    user.uid = auth['uid']
    if auth['info']
      user.name = auth['info']['name'] || ""
      user.email = auth['info']['email'] || ""
    end
  end
end


def facebook
    @facebook ||= Koala::Facebook::API.new('BAAIGh00LCBEBAJ8rTtbjwtUUdUKBRZBUOCWlVEZAS3ZCEyzHtJ7FyG7tYGjFMLEAMiKQnOvI0Gl4c7AWTpF5z2iKynfUGAKDb5F5GN4UG5QOrSsE8PCXlee6d3nsZCrGujL0SGGGnyI3XvPQQHNAbYtZAs15kF5f4N87h0JVD3jGcBm47ofsdWOgCUjUItz5AjFHuGACumJQYyq94lzR722lnszxah9GZApdGgzaoLqCwXPwyvJ7NZB')
    block_given? ? yield(@facebook) : @facebook
  rescue Koala::Facebook::APIError => e
    logger.info e.to_s
    nil
  end
  
  def friends_count
    facebook { |fb| fb.get_connection("me", "friends").size}
  end

 def friends_list
    facebook { |fb| fb.get_connection('me','friends',:fields=>"name,relationship_status,location")}
  end

   def status_single_friend
   # facebook { |fb| fb.get_connection('me','friends',:fields=>"name,gender,relationship_status")}
    facebook.fql_query("select uid, name, relationship_status from user WHERE relationship_status='married' AND uid in (select uid2 from friend where uid1 = me())")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery



  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  # GET /locations
  # GET /locations.json
  def index

#@graph = Koala::Facebook::API.new('BAACEdEose0cBAOndIZCjcaTGliFZBWIMRDpuOvdW8hPHiWR15a01jTuTIfJGScE1lzbpjDMBWdNZBQVySazBdh3vl9Oo86dk40a2zRrE3C1xM6rxqghJaxnKgh3gbm3ZAQiWP9utcv0YGWebRYIMvOptIyCU8X5bIuPutHFYYHiP92ZADPTZC7i5vQOjYD4LDVPOy0TO4iTCLKHec7UljToPBFYDfqgFCZCSgrB99A1LREpdjwEaZBse')
#@hello = @graph.get_object("my.Name")
#render :text=>'<pre>' + @hello.to_yaml and return
#@graph = Koala::Facebook::API.new('BAACEdEose0cBAFUHbYr2brBqwStJq42VlGXZAi10CwqZCoSP1PC7AAfwzkGHEwv8j5YRklCEIXo7cgPbrQcZCVeVpNtXtb20QhOAcrHIzZArmoSpxmIFZB6pnFMsiGdE065WNYTlnxJnV3MXZAm1rCdGcgCIhOREZByr9Mcq4cKObQlPOVpXZAS1vgfJktiNROULr27mhxEroAyu7B0fl9EoTcKQcOmvasHWHbjsd4rkdQZDZD')

#profile = @graph.get_object("me")
#friends = @graph.get_connections("me", "friends")
# render :text=>'<pre>' + friends.to_yaml and return
if params[:search].present?
    @locations = Location.near(params[:search], 50, :order => :distance)
  else
    @locations = Location.all
  end
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @locations }
    end
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
    @location = Location.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @location }
    end
  end

  # GET /locations/new
  # GET /locations/new.json
  def new
    @location = Location.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @location }
    end
  end

  # GET /locations/1/edit
  def edit
    @location = Location.find(params[:id])
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(params[:location])

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render json: @location, status: :created, location: @location }
      else
        format.html { render action: "new" }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /locations/1
  # PUT /locations/1.json
  def update
    @location = Location.find(params[:id])

    respond_to do |format|
      if @location.update_attributes(params[:location])
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location = Location.find(params[:id])
    @location.destroy

    respond_to do |format|
      format.html { redirect_to locations_url }
      format.json { head :no_content }
    end
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

		def new
          redirect_to '/auth/facebook'
		end

		def create
			  auth = request.env['omniauth.auth']
 			   user = User.where(:provider => auth['provider'], :uid => auth['uid']).first || User.create_with_omniauth(auth)
			   #render :text=>'<pre>' + auth.to_yaml and return
               session[:user_id] = user.id
               

               redirect_to locations_path, :notice=>"You are login successfully"


			 # @authorization = User.find_by_provider_and_uid(auth_hash["provider"], auth_hash["uid"])
  #redirect_to root_url, :notice => "Signed in!"
			 #  if @authorization
			 #    render :text => "Welcome back #{@authorization.user.name}! You have already signed up."
		  # else
			 #    user = User.new :name => auth_hash["user_info"]["name"], :email => auth_hash["user_info"]["email"]
    #             
			 #    user.authorizations.build :provider => auth_hash["provider"], :uid => auth_hash["uid"]
			 #    user.save
			 
			 #    render :text => "Hi #{user.name}! You've signed up."
			 #  end
        end


	   def destroy
	     session[:user_id] = nil
	     redirect_to root_url
	   end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>My Google App</title>
  <script src="http://connect.facebook.net/en_US/all.js"></script>
	<script language="javascript" type="text/javascript">
	    FB.init({
		 appId: 570128136341521,
		 xfbml: true,
		 cookie: true,
		 oauth: true
	       });

	</script>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

</head>
<body>
<div id="header">
<h1>Find Your Location</h1>
</div>
<br/></br/>
<%= yield %>

<div id="fb-root">
<fb:login-button autologoutlink="true" onlogin="OnRequestPermission();" scope="user_about_me,user_activities,user_birthday,user_online_presence">
</fb:login-button>

&nbsp;&nbsp;

<%= link_to image_tag('send_request_en.gif'), '#', :id => :app_request, :class=>"test"%>&nbsp;&nbsp;<%= link_to image_tag('Share_Your_Experience.jpg'), '#', :id => :post_comments %>


<div >



<script language="javascript" type="text/javascript">

 $('#app_request').click(function () {
    FB.ui({
      method: 'apprequests',
      message: 'Hi This is my test app developed in RoR and integrated in FB',
      data: 'Stores important links of user'
    });
return false;
  });




$('#post_comments').click(function () {

        // calling the API ...
        var obj = {
          method: 'feed',
          link: 'http://apps.facebook.com/265171790218414/',
          picture: 'http://cdn1.iconfinder.com/data/icons/softwaredemo/PNG/256x256/User1.png',
          name: 'Aloo App',
          caption: 'Using RoR and FaceBook',
          description: 'Integrated RoR app in Facebook through canvas'
        };
        FB.ui(obj);
       return false;
      });


</script>
</body>
</html>

app/views/locations/_form.html.erb
<%= form_for(@location) do |f| %>
  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% @location.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :address, :placeholder=>"Enter Address to see map...." %>
  </div>
 
  <div class="actions">
    <%= f.submit "view" %>
  </div>
<% end %>

app/views/locations/edit.html.erb
<h1>Editing location</h1>

<%= render 'form' %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/index.html.erb
<%= form_tag locations_path, :method => :get do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search Near", :name => nil %>
<% end %>
<table>
  <tr>
    <th>Address</th>
    <th>Latitude</th>
    <th>Longitude</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @locations.each do |location| %>
  <tr>
    <td><%= location.address %></td>
    <td><%= location.latitude %></td>
    <td><%= location.longitude %></td>
    <td><%= link_to 'Show', location %></td>
    <td><%= link_to 'Edit', edit_location_path(location) %></td>
    <td><%= link_to 'Destroy', location, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Location', new_location_path %>
<br/>
<br/>



<br/>
<br/>
<fieldset>
<legend>Friends Count</legend>


  <% if current_user %>
  Number of Friends: <%= current_user.friends_count %>
<% end %>
</fieldset>


<br />

<fieldset>
  <legend>All Friend List</legend>
<% if current_user  %>
<table border=1>
  <tr>
    <th>Id</th>
    <th>Name</th>
    <th>Status</th>
    <th>Loction</th>

  </tr>
    <% for friend in current_user.friends_list  %>
          <tr>
            <td><b><%= friend["id"]%> </b></td>
          
         
            <td><%= friend["name"] %></td>
         
           <td><%= friend["relationship_status"]%></td>
          <td><%= friend["location"]["name"] %></td>
          </tr>
        <% end %>
    <table>
<% end %>
</fieldset>



<fieldset>
  <legend>Single Status Friend List</legend>
<% if current_user  %>
<table border=1>
  <tr>
    <th>Id</th>
    <th>Name</th>
    <th>Status</th>
  </tr>
    <% for friend in current_user.status_single_friend  %>
          <tr>
            <td><b><%= friend["id"]%> </b></td>
          
         
            <td><%= friend["name"] %></td>
         
           <td><%= friend["relationship_status"]%></td>

          </tr>
        <% end %>
    <table>
<% end %>
</fieldset>






<% if session[:user_id].blank? %>
 <p><%= link_to 'Sign in with Facebook', signin_path %></p>
 <%else%>
 <%= link_to 'logout', signout_path %> 
<%end%>

app/views/locations/new.html.erb
<%= render 'form' %>

 <% if session[:user_id].blank? %>
 <p><%= link_to 'Sign in with Facebook', signin_path %></p>
 <%else%>
 <%= link_to 'logout', signout_path %> 
<%end%>
<%#= link_to 'Back', locations_path %>

app/views/locations/show.html.erb
<p>
  <strong>Address:</strong>
  <%= @location.address %>
</p>
<p>
  <strong>Latitude:</strong>
  <%= @location.latitude %>
</p>
<p>
  <strong>Longitude:</strong>
  <%= @location.longitude %>
</p>

<h3>Nearby Locations</h3>
<ul>
<%if !@location.blank?%>
<% for location in @location.nearbys(10) %>
  <li><%= link_to location.address, location %> (<%= location.distance.round(2) %> miles)</li>
<% end %>
</ul>
<%end%>
<%#= image_tag "http://maps.googleapis.com/maps/api/streetview?size=200x200&location=40.720032,%20-73.988354&heading=235&sensor=false" %>
<%= image_tag "http://maps.googleapis.com/maps/api/staticmap?size=500x500&sensor=false&zoom=16&markers=#{@location.latitude}%2C#{@location.longitude}" %>


<p>
  <%= link_to "click here to find new location", new_location_path %>
</p>